### ISSUE TITLE
Test runner in style mode error

### ISSUE THREAD

**Issue by denismaier** [Juris-M/citeproc-test-runner#7]
I've just installed the test runner but I cannot run a test with `-a`. I always get the message: 
"Error: Running in styleMode. The -w option is required. Add -h for help."

**Comment by denismaier** [comment]
Looks like `-a` only works if I am in a `citeproc-js` development folder?

**Comment by fbennett** [comment]
It needs to be documented, but the test runner operates in one of two modes.
Inside the citeproc-js repo, it is used to test the processor, and runs its
tests with bare `cslrun -a`. Outside of the citeproc-js repo, it is used to
test styles. The first file specified with the -w option is both watched
for changes, and parsed for its ID. The ID is used to pick a directory of
test fixtures aimed at that style. The -a, -g, and -s options then take
effect to select which tests in the style-specific test directory should be
run. The -U option will check all items in the chosen online repo (main or
submission queue), within the collection corresponding to the style ID, for
reflection in the style tests directory, generating tests for any items
that lack a test. Once generated with -U, a test will not be overwritten,
and can be manually tweaked to taste.

**Comment by fbennett** [comment]
As a further note, the tests generated with -U will look a bit different from the processor tests in the standard suite and the processor repo: they omit the CSL section (because the code of the specified style is used): they include a KEYS section that tracks correspondence with the style-test items library collection; and they run in a novel "all" mode that tests the style in all of the citation forms that it can produce.

**Comment by denismaier** [comment]
Thanks for the explanation. It's much clearer now.
